Repository pribos/pribos, pull requests merged in 2022-08, with the labels that each got.

#8 setting:7:added .gitignore
  .gitignore
  BE/temp.md
  FE/temp.md
Labels: setting

#10 setting:9:add git template and codeowners
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
Labels: setting

#11 setting:3:backend setting, user & task model
  BE/temp.md
  backend/account/__init__.py
  backend/account/admin.py
  backend/account/apps.py
  backend/account/managers.py
  backend/account/migrations/0001_initial.py
  backend/account/migrations/__init__.py
  backend/account/models.py
  backend/account/serializers.py
  backend/account/tests.py
  backend/account/urls.py
  backend/account/views.py
  backend/backend/__init__.py
  backend/backend/asgi.py
  backend/backend/settings/__init__.py
  backend/backend/settings/base.py
  backend/backend/settings/local.py
  backend/backend/settings/production.py
  backend/backend/setup.cfg
  backend/backend/urls.py
  backend/backend/wsgi.py
  backend/common/__init__.py
  backend/common/admin.py
  backend/common/apps.py
  backend/common/exceptions.py
  backend/common/migrations/__init__.py
  backend/common/models.py
  backend/common/tests.py
  backend/common/urls.py
  backend/common/views.py
  backend/manage.py
  backend/requirements/base.txt
  backend/requirements/local.txt
  backend/requirements/production.txt
  backend/task/__init__.py
  backend/task/admin.py
  backend/task/apps.py
  backend/task/migrations/0001_initial.py
  backend/task/migrations/__init__.py
  backend/task/models.py
  backend/task/serializers.py
  backend/task/tests.py
  backend/task/urls.py
  backend/task/views.py
  frontend/temp.md
Labels: setting, feature

#12 chore:9:git codeowner 수정
  .github/CODEOWNERS
Labels: fix

#16 chore:9:fix code quality issues
  backend/account/admin.py
  backend/account/apps.py
  backend/account/managers.py
  backend/account/migrations/0001_initial.py
  backend/account/models.py
  backend/account/serializers.py
  backend/account/urls.py
  backend/backend/settings/base.py
  backend/backend/settings/local.py
  backend/backend/settings/production.py
  backend/backend/urls.py
  backend/common/apps.py
  backend/common/exceptions.py
  backend/common/models.py
  backend/common/urls.py
  backend/common/views.py
  backend/manage.py
  backend/setup.cfg
  backend/task/admin.py
  backend/task/apps.py
  backend/task/migrations/0001_initial.py
  backend/task/models.py
  backend/task/serializers.py
  backend/task/urls.py
  backend/task/views.py
Labels: fix

#13 setting:1:setup with vite
  frontend/.gitignore
  frontend/index.html
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/temp.md
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  frontend/yarn.lock
Labels: setting

#20 setting:#18:added codeonwers and fixed pr template
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
Labels: setting

#14 feat:6:developing regex
  data/infomation_extraction_from_mail.py
Labels: feature

#24 setting:#23:added esline, prettier
  frontend/.eslintrc.json
  frontend/.prettierrc
  frontend/package.json
  frontend/yarn.lock
Labels: setting

#27 fix:#3:modify task model
  backend/backend/settings/base.py
  backend/task/models.py
  backend/task/views.py
Labels: fix

#28 17
  .gitignore
  backend/account/migrations/__init__.py
  backend/account/urls.py
  backend/account/views.py
  backend/accounts/__init__.py
  backend/accounts/admin.py
  backend/accounts/apps.py
  backend/accounts/managers.py
  backend/accounts/models.py
  backend/accounts/serializers.py
  backend/accounts/tests.py
  backend/accounts/urls.py
  backend/accounts/views.py
  backend/backend/urls.py
Labels: feature
