Repository pribos/pribos, pull requests merged in 2022-09, with the labels that each got.

#32 21
  .gitignore
  Dockerfile
  backend/Dockerfile
  backend/accounts/migrations/__init__.py
  backend/backend/settings/local.py
  backend/requirements/base.txt
  backend/requirements/local.txt
  backend/requirements/production.txt
  backend/start.sh
  docker-compose.yml
Labels: feature

#34 33
  Dockerfile
  backend/Dockerfile
  backend/requirements/base.txt
  backend/start.sh
  docker-compose.yml
Labels: fix

#36 35
  .github/workflows/aws.yml
  Dockerfile
Labels: setting

#37 33
  Dockerfile
  backend/backend/urls.py
Labels: fix

#38 35
  .github/workflows/aws.yml
  .gitignore
  Dockerfile
  backend/.env.local
  backend/backend/settings/base.py
  backend/backend/settings/local.py
  backend/backend/settings/production.py
  backend/manage.py
Labels: fix

#39 35
  .github/workflows/aws.yml
  backend/manage.py
Labels: fix

#25 feat:#23:added router and pages
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/main.tsx
  frontend/src/pages/Calendar.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Mailbox.tsx
  frontend/yarn.lock
Labels: feature

#55 21
  .github/workflows/aws.yml
  .gitignore
  Dockerfile
  backend/.env.local
  backend/backend/settings/base.py
  backend/backend/settings/local.py
  backend/backend/settings/production.py
  backend/backend/urls.py
  backend/manage.py
  backend/requirements/base.txt
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/main.tsx
  frontend/src/pages/Calendar.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Mailbox.tsx
  frontend/yarn.lock
Labels: fix
